version: "3.8"

services:
  # Define our web service
  web:
    # Build from Dockerfile in current directory
    build: .

    # Map container port from .env file
    ports:
      - "${PORT}:${PORT}"

    # Mount volumes for hot-reload (code changes reflect immediately)
    volumes:
      - .:/app

    # Environment variables
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - PORT=${PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

    # Restart policy: container will restart unless stopped manually
    restart: unless-stopped

    # Add dependency on database
    depends_on:
      - db

  # PostgreSQL Service
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

# Define volumes
volumes:
  postgres_data:
