version: '3'
services:
  jobmanager:
    image: flink:1.16.1
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.bind-address: 0.0.0.0
    volumes:
      - ./data:/data
      - ./code:/code

  taskmanager:
    image: flink:1.16.1
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        taskmanager.numberOfTaskSlots: 2
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./data:/data
      - ./code:/code 