version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ./data:/data

  jobmanager:
    image: flink:1.16.1
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.bind-address: 0.0.0.0
    volumes:
      - ./data:/data
      - ./code:/code

  taskmanager:
    image: flink:1.16.1
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        taskmanager.numberOfTaskSlots: 4
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./data:/data
      - ./code:/code
      
  python:
    image: python:3.9
    container_name: python-tools
    depends_on:
      - jobmanager
      - kafka
    volumes:
      - ./data:/data
      - ./code:/code
    working_dir: /code
    command: bash -c "pip install -r requirements.txt && python -m http.server 8888"
    
  maven:
    image: maven:3.8-openjdk-11
    container_name: maven-builder
    volumes:
      - ./code:/code
      - ./data:/data
      - $HOME/.m2:/root/.m2
    working_dir: /code/kafka
    command: tail -f /dev/null 