name: 'ecommerce_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ecommerce_dbt'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  ecommerce_dbt:
    # Config applied to all models
    +materialized: view
    sources:
      +materialized: view
    staging:
      +materialized: view
    core:
      +materialized: table 