kafka:
  bootstrap_servers: "localhost:9092"
  topics:
    eth_blocks: "ethereum-blocks"
    eth_transactions: "ethereum-transactions"
    filtered_transactions: "ethereum-filtered-transactions"
    high_value_transactions: "ethereum-high-value-transactions"
  consumer_group: "ethereum-consumer-group"

ethereum:
  providers:
    llamarpc: "https://eth.llamarpc.com"
    infura: "https://mainnet.infura.io/v3/YOUR_INFURA_KEY"
    alchemy: "https://eth-mainnet.g.alchemy.com/v2/YOUR_ALCHEMY_KEY"
  default_provider: "llamarpc"
  polling_interval: 10  # seconds

processing:
  high_value_threshold: 1.0  # ETH 