version: '3'

services:
  postgres:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: dbt_db_ex3
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d 