ecommerce_datamart:
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5434
      user: dbt_user
      password: dbt_password
      dbname: dbt_db_ex3
      schema: public
  target: dev 